api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
    exception_to_status:
        App\Exception\ErrorActionCallException: 400
        App\Exception\UserExistInAnyGroupException: 400
