#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POS

api:
  path: /api
  controller: App\Controller\AuthController::api

login_check:
  path: /login_check
  methods: [POST]

token_tester:
  path: /token_tester
  controller: App\Controller\AuthController::testToken
  methods: [POST]

gesdinet_jwt_refresh_token:
    path: /login_refresh
    controller: gesdinet.jwtrefreshtoken::refresh